# Generated by Django 3.0.7 on 2020-07-08 18:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200708_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 18, 10, 56, 365934, tzinfo=utc)),
        ),
    ]
