# Generated by Django 3.0.7 on 2020-07-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200710_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='activity',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Close')], default='O', max_length=1),
        ),
    ]
