# Generated by Django 3.0.7 on 2020-07-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='activity',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='O', max_length=1),
        ),
    ]
